# -*- coding: utf-8 -*-
"""Assignment 4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bZjhuFfT5IPxOAWoe4m3EEfZnc4Ta2EN
"""

def top_student(students):
  if len(students) == 0:
    print('No student available.')
    return

    top = students[0]

    for student in students:
      if students [2] > top [2]:
        top = student
    print(f'Top student is {top[0]} with {top[2]}')

